title: "Javier Julio"
email: "jjfutbol@gmail.com"
description: >-
  A Brooklyn based full stack developer with an eye for
  design and details. Currently, designing, building and
  automating solutions at Jackpocket in NYC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://javierjulio.com" # the base hostname & protocol for your site
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-autoprefixer
  - jekyll-redirect-from
  - jekyll-sitemap
autoprefixer:
  only_production: true
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:title/
collections:
  recipes:
    output: true
    permalink: /recipes/:path/
  presentations:
    output: true
    permalink: /presentations/:path/
