title: Javier Julio
email: jjfutbol@gmail.com
description: "A Brooklyn based full stack software engineer with an eye for design and details."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://javierjulio.com" # the base hostname & protocol for your site
twitter_username: javierjulio
github_username: javierjulio
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-autoprefixer
  - jekyll-redirect-from

autoprefixer:
  only_production: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /blog/:title/

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
  presentations:
    output: true
    permalink: /presentations/:path/
