name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2'
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Cache HTMLProofer
      id: cache-htmlproofer
      uses: actions/cache@v4
      with:
        path: tmp/.htmlproofer
        key: ${{ runner.os }}-htmlproofer
    - name: Run Tests
      run: |
        bundle exec rake
